/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 101
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_LT = 3,
  anon_sym_GT = 4,
  anon_sym_STAR = 5,
  anon_sym_unsigned = 6,
  anon_sym_int = 7,
  anon_sym_hyper = 8,
  anon_sym_float = 9,
  anon_sym_double = 10,
  anon_sym_quadruple = 11,
  anon_sym_bool = 12,
  anon_sym_LBRACE = 13,
  anon_sym_EQ = 14,
  anon_sym_COMMA = 15,
  anon_sym_RBRACE = 16,
  anon_sym_SEMI = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_COLON = 20,
  anon_sym_0 = 21,
  aux_sym_decimal_constant_token1 = 22,
  sym_hexadecimal_constant = 23,
  sym_octal_constant = 24,
  sym_keyword_case = 25,
  sym_keyword_opaque = 26,
  sym_keyword_string = 27,
  sym_keyword_void = 28,
  sym_keyword_union = 29,
  sym_keyword_switch = 30,
  sym_keyword_typedef = 31,
  sym_keyword_const = 32,
  sym_keyword_enum = 33,
  sym_keyword_struct = 34,
  sym_keyword_default = 35,
  sym_identifier = 36,
  sym_block_comment = 37,
  sym_source_file = 38,
  sym_declaration = 39,
  sym_value = 40,
  sym_constant = 41,
  sym_type_specifier = 42,
  sym_enum_type_spec = 43,
  sym_enum_body = 44,
  sym_struct_type_spec = 45,
  sym_struct_body = 46,
  sym_union_type_spec = 47,
  sym_union_body = 48,
  sym_case_spec = 49,
  sym_constant_def = 50,
  sym_type_def = 51,
  sym_definition = 52,
  sym_decimal_constant = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_enum_body_repeat1 = 55,
  aux_sym_struct_body_repeat1 = 56,
  aux_sym_union_body_repeat1 = 57,
  aux_sym_case_spec_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_STAR] = "*",
  [anon_sym_unsigned] = "unsigned",
  [anon_sym_int] = "int",
  [anon_sym_hyper] = "hyper",
  [anon_sym_float] = "float",
  [anon_sym_double] = "double",
  [anon_sym_quadruple] = "quadruple",
  [anon_sym_bool] = "bool",
  [anon_sym_LBRACE] = "{",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_0] = "0",
  [aux_sym_decimal_constant_token1] = "decimal_constant_token1",
  [sym_hexadecimal_constant] = "hexadecimal_constant",
  [sym_octal_constant] = "octal_constant",
  [sym_keyword_case] = "keyword_case",
  [sym_keyword_opaque] = "keyword_opaque",
  [sym_keyword_string] = "keyword_string",
  [sym_keyword_void] = "keyword_void",
  [sym_keyword_union] = "keyword_union",
  [sym_keyword_switch] = "keyword_switch",
  [sym_keyword_typedef] = "keyword_typedef",
  [sym_keyword_const] = "keyword_const",
  [sym_keyword_enum] = "keyword_enum",
  [sym_keyword_struct] = "keyword_struct",
  [sym_keyword_default] = "keyword_default",
  [sym_identifier] = "identifier",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_value] = "value",
  [sym_constant] = "constant",
  [sym_type_specifier] = "type_specifier",
  [sym_enum_type_spec] = "enum_type_spec",
  [sym_enum_body] = "enum_body",
  [sym_struct_type_spec] = "struct_type_spec",
  [sym_struct_body] = "struct_body",
  [sym_union_type_spec] = "union_type_spec",
  [sym_union_body] = "union_body",
  [sym_case_spec] = "case_spec",
  [sym_constant_def] = "constant_def",
  [sym_type_def] = "type_def",
  [sym_definition] = "definition",
  [sym_decimal_constant] = "decimal_constant",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_enum_body_repeat1] = "enum_body_repeat1",
  [aux_sym_struct_body_repeat1] = "struct_body_repeat1",
  [aux_sym_union_body_repeat1] = "union_body_repeat1",
  [aux_sym_case_spec_repeat1] = "case_spec_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_unsigned] = anon_sym_unsigned,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_hyper] = anon_sym_hyper,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_double] = anon_sym_double,
  [anon_sym_quadruple] = anon_sym_quadruple,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_0] = anon_sym_0,
  [aux_sym_decimal_constant_token1] = aux_sym_decimal_constant_token1,
  [sym_hexadecimal_constant] = sym_hexadecimal_constant,
  [sym_octal_constant] = sym_octal_constant,
  [sym_keyword_case] = sym_keyword_case,
  [sym_keyword_opaque] = sym_keyword_opaque,
  [sym_keyword_string] = sym_keyword_string,
  [sym_keyword_void] = sym_keyword_void,
  [sym_keyword_union] = sym_keyword_union,
  [sym_keyword_switch] = sym_keyword_switch,
  [sym_keyword_typedef] = sym_keyword_typedef,
  [sym_keyword_const] = sym_keyword_const,
  [sym_keyword_enum] = sym_keyword_enum,
  [sym_keyword_struct] = sym_keyword_struct,
  [sym_keyword_default] = sym_keyword_default,
  [sym_identifier] = sym_identifier,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_value] = sym_value,
  [sym_constant] = sym_constant,
  [sym_type_specifier] = sym_type_specifier,
  [sym_enum_type_spec] = sym_enum_type_spec,
  [sym_enum_body] = sym_enum_body,
  [sym_struct_type_spec] = sym_struct_type_spec,
  [sym_struct_body] = sym_struct_body,
  [sym_union_type_spec] = sym_union_type_spec,
  [sym_union_body] = sym_union_body,
  [sym_case_spec] = sym_case_spec,
  [sym_constant_def] = sym_constant_def,
  [sym_type_def] = sym_type_def,
  [sym_definition] = sym_definition,
  [sym_decimal_constant] = sym_decimal_constant,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_enum_body_repeat1] = aux_sym_enum_body_repeat1,
  [aux_sym_struct_body_repeat1] = aux_sym_struct_body_repeat1,
  [aux_sym_union_body_repeat1] = aux_sym_union_body_repeat1,
  [aux_sym_case_spec_repeat1] = aux_sym_case_spec_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unsigned] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hyper] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_double] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_quadruple] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_decimal_constant_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_hexadecimal_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_octal_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_case] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_opaque] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_string] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_void] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_union] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_switch] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_typedef] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_const] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_default] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_type_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_type_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_body] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_type_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_body] = {
    .visible = true,
    .named = true,
  },
  [sym_union_type_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_union_body] = {
    .visible = true,
    .named = true,
  },
  [sym_case_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_def] = {
    .visible = true,
    .named = true,
  },
  [sym_type_def] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_constant] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_case_spec_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(83);
      ADVANCE_MAP(
        '(', 108,
        ')', 109,
        '*', 88,
        ',', 105,
        '/', 2,
        '0', 111,
        ':', 110,
        ';', 107,
        '<', 86,
        '=', 104,
        '>', 87,
        '[', 84,
        ']', 85,
        'b', 53,
        'c', 7,
        'd', 19,
        'e', 49,
        'f', 39,
        'h', 79,
        'i', 44,
        'o', 56,
        'q', 75,
        's', 66,
        't', 80,
        'u', 45,
        'v', 52,
        '{', 103,
        '}', 106,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(88);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '0') ADVANCE(111);
      if (lookahead == ';') ADVANCE(107);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(112);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(192);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '/', 2,
        'b', 170,
        'c', 136,
        'd', 168,
        'e', 164,
        'f', 157,
        'h', 189,
        'i', 162,
        'o', 172,
        'q', 186,
        's', 180,
        'u', 160,
        'v', 166,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '/', 2,
        'b', 170,
        'd', 168,
        'e', 164,
        'f', 157,
        'h', 189,
        'i', 162,
        'o', 172,
        'q', 186,
        's', 180,
        'u', 160,
        'v', 166,
        '}', 106,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(64);
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(60);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(69);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(70);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(122);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(89);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(63);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(118);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 28:
      if (lookahead == 'f') ADVANCE(127);
      END_STATE();
    case 29:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 30:
      if (lookahead == 'g') ADVANCE(120);
      END_STATE();
    case 31:
      if (lookahead == 'g') ADVANCE(50);
      END_STATE();
    case 32:
      if (lookahead == 'h') ADVANCE(126);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(55);
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(101);
      END_STATE();
    case 39:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 43:
      if (lookahead == 'm') ADVANCE(129);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(67);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(124);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 53:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 56:
      if (lookahead == 'p') ADVANCE(8);
      END_STATE();
    case 57:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 58:
      if (lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 59:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 60:
      if (lookahead == 'q') ADVANCE(78);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(76);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(68);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(61);
      if (lookahead == 'w') ADVANCE(34);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(91);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(128);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(95);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(131);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(133);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 73:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 74:
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 75:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 76:
      if (lookahead == 'u') ADVANCE(59);
      END_STATE();
    case 77:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 78:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 79:
      if (lookahead == 'y') ADVANCE(57);
      END_STATE();
    case 80:
      if (lookahead == 'y') ADVANCE(58);
      END_STATE();
    case 81:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(115);
      END_STATE();
    case 82:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(114);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_unsigned);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_unsigned);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_hyper);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_hyper);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_float);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_double);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_double);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_quadruple);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_quadruple);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_0);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(81);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(82);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_decimal_constant_token1);
      if (lookahead == '0') ADVANCE(113);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_decimal_constant_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_hexadecimal_constant);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_octal_constant);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_keyword_case);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_keyword_case);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_keyword_opaque);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_keyword_opaque);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_keyword_string);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_keyword_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_keyword_void);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_keyword_void);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_keyword_union);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_keyword_union);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_keyword_switch);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_keyword_typedef);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_keyword_const);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_keyword_enum);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_keyword_enum);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_keyword_struct);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_keyword_struct);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_keyword_default);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(175);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(179);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(182);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(156);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(183);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(178);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(163);
      if (lookahead == 'u') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(171);
      if (lookahead == 's') ADVANCE(151);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(169);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(145);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(154);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(181);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(185);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(148);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(152);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(155);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(184);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(167);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(147);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(158);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'q') ADVANCE(188);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(153);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(187);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(146);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(159);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(173);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(191);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(190);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(191);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_unsigned] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_hyper] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_double] = ACTIONS(1),
    [anon_sym_quadruple] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [aux_sym_decimal_constant_token1] = ACTIONS(1),
    [sym_hexadecimal_constant] = ACTIONS(1),
    [sym_octal_constant] = ACTIONS(1),
    [sym_keyword_case] = ACTIONS(1),
    [sym_keyword_opaque] = ACTIONS(1),
    [sym_keyword_string] = ACTIONS(1),
    [sym_keyword_void] = ACTIONS(1),
    [sym_keyword_union] = ACTIONS(1),
    [sym_keyword_switch] = ACTIONS(1),
    [sym_keyword_typedef] = ACTIONS(1),
    [sym_keyword_const] = ACTIONS(1),
    [sym_keyword_enum] = ACTIONS(1),
    [sym_keyword_struct] = ACTIONS(1),
    [sym_keyword_default] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(76),
    [sym_constant_def] = STATE(27),
    [sym_type_def] = STATE(27),
    [sym_definition] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_keyword_union] = ACTIONS(7),
    [sym_keyword_typedef] = ACTIONS(9),
    [sym_keyword_const] = ACTIONS(11),
    [sym_keyword_enum] = ACTIONS(13),
    [sym_keyword_struct] = ACTIONS(15),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(17), 1,
      anon_sym_unsigned,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 1,
      sym_keyword_opaque,
    ACTIONS(28), 1,
      sym_keyword_string,
    ACTIONS(31), 1,
      sym_keyword_void,
    ACTIONS(34), 1,
      sym_keyword_union,
    ACTIONS(37), 1,
      sym_keyword_enum,
    ACTIONS(40), 1,
      sym_keyword_struct,
    STATE(2), 1,
      aux_sym_struct_body_repeat1,
    STATE(60), 1,
      sym_type_specifier,
    STATE(86), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(20), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [51] = 14,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(47), 1,
      sym_keyword_case,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    STATE(12), 1,
      aux_sym_case_spec_repeat1,
    STATE(60), 1,
      sym_type_specifier,
    STATE(91), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [102] = 14,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      aux_sym_struct_body_repeat1,
    STATE(60), 1,
      sym_type_specifier,
    STATE(86), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [153] = 14,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_struct_body_repeat1,
    STATE(60), 1,
      sym_type_specifier,
    STATE(86), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [204] = 14,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(47), 1,
      sym_keyword_case,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    STATE(3), 1,
      aux_sym_case_spec_repeat1,
    STATE(60), 1,
      sym_type_specifier,
    STATE(85), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [255] = 12,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    STATE(60), 1,
      sym_type_specifier,
    STATE(97), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [300] = 12,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    STATE(60), 1,
      sym_type_specifier,
    STATE(87), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [345] = 12,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    STATE(60), 1,
      sym_type_specifier,
    STATE(71), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [390] = 12,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    STATE(60), 1,
      sym_type_specifier,
    STATE(94), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [435] = 12,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      anon_sym_unsigned,
    ACTIONS(49), 1,
      sym_keyword_opaque,
    ACTIONS(51), 1,
      sym_keyword_string,
    ACTIONS(53), 1,
      sym_keyword_void,
    ACTIONS(55), 1,
      sym_keyword_union,
    ACTIONS(57), 1,
      sym_keyword_enum,
    ACTIONS(59), 1,
      sym_keyword_struct,
    STATE(60), 1,
      sym_type_specifier,
    STATE(72), 1,
      sym_declaration,
    STATE(64), 3,
      sym_enum_type_spec,
      sym_struct_type_spec,
      sym_union_type_spec,
    ACTIONS(45), 7,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_identifier,
  [480] = 4,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(67), 1,
      sym_keyword_case,
    STATE(12), 1,
      aux_sym_case_spec_repeat1,
    ACTIONS(65), 14,
      anon_sym_unsigned,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_keyword_opaque,
      sym_keyword_string,
      sym_keyword_void,
      sym_keyword_union,
      sym_keyword_enum,
      sym_keyword_struct,
      sym_identifier,
  [506] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(70), 15,
      anon_sym_unsigned,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_keyword_case,
      sym_keyword_opaque,
      sym_keyword_string,
      sym_keyword_void,
      sym_keyword_union,
      sym_keyword_enum,
      sym_keyword_struct,
      sym_identifier,
  [527] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(72), 14,
      anon_sym_unsigned,
      anon_sym_int,
      anon_sym_hyper,
      anon_sym_float,
      anon_sym_double,
      anon_sym_quadruple,
      anon_sym_bool,
      sym_keyword_opaque,
      sym_keyword_string,
      sym_keyword_void,
      sym_keyword_union,
      sym_keyword_enum,
      sym_keyword_struct,
      sym_identifier,
  [550] = 9,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(7), 1,
      sym_keyword_union,
    ACTIONS(9), 1,
      sym_keyword_typedef,
    ACTIONS(11), 1,
      sym_keyword_const,
    ACTIONS(13), 1,
      sym_keyword_enum,
    ACTIONS(15), 1,
      sym_keyword_struct,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    STATE(16), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(27), 2,
      sym_constant_def,
      sym_type_def,
  [580] = 9,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      sym_keyword_union,
    ACTIONS(81), 1,
      sym_keyword_typedef,
    ACTIONS(84), 1,
      sym_keyword_const,
    ACTIONS(87), 1,
      sym_keyword_enum,
    ACTIONS(90), 1,
      sym_keyword_struct,
    STATE(16), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(27), 2,
      sym_constant_def,
      sym_type_def,
  [610] = 8,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(93), 1,
      anon_sym_0,
    ACTIONS(95), 1,
      aux_sym_decimal_constant_token1,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(26), 1,
      sym_decimal_constant,
    STATE(33), 1,
      sym_constant,
    STATE(37), 1,
      sym_value,
    ACTIONS(97), 2,
      sym_hexadecimal_constant,
      sym_octal_constant,
  [636] = 8,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(93), 1,
      anon_sym_0,
    ACTIONS(95), 1,
      aux_sym_decimal_constant_token1,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(26), 1,
      sym_decimal_constant,
    STATE(33), 1,
      sym_constant,
    STATE(74), 1,
      sym_value,
    ACTIONS(97), 2,
      sym_hexadecimal_constant,
      sym_octal_constant,
  [662] = 8,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(93), 1,
      anon_sym_0,
    ACTIONS(95), 1,
      aux_sym_decimal_constant_token1,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(26), 1,
      sym_decimal_constant,
    STATE(33), 1,
      sym_constant,
    STATE(67), 1,
      sym_value,
    ACTIONS(97), 2,
      sym_hexadecimal_constant,
      sym_octal_constant,
  [688] = 8,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(93), 1,
      anon_sym_0,
    ACTIONS(95), 1,
      aux_sym_decimal_constant_token1,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(26), 1,
      sym_decimal_constant,
    STATE(33), 1,
      sym_constant,
    STATE(89), 1,
      sym_value,
    ACTIONS(97), 2,
      sym_hexadecimal_constant,
      sym_octal_constant,
  [714] = 8,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(93), 1,
      anon_sym_0,
    ACTIONS(95), 1,
      aux_sym_decimal_constant_token1,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(26), 1,
      sym_decimal_constant,
    STATE(33), 1,
      sym_constant,
    STATE(73), 1,
      sym_value,
    ACTIONS(97), 2,
      sym_hexadecimal_constant,
      sym_octal_constant,
  [740] = 8,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(93), 1,
      anon_sym_0,
    ACTIONS(95), 1,
      aux_sym_decimal_constant_token1,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(26), 1,
      sym_decimal_constant,
    STATE(33), 1,
      sym_constant,
    STATE(57), 1,
      sym_value,
    ACTIONS(97), 2,
      sym_hexadecimal_constant,
      sym_octal_constant,
  [766] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_keyword_union,
      sym_keyword_typedef,
      sym_keyword_const,
      sym_keyword_enum,
      sym_keyword_struct,
  [778] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(103), 6,
      ts_builtin_sym_end,
      sym_keyword_union,
      sym_keyword_typedef,
      sym_keyword_const,
      sym_keyword_enum,
      sym_keyword_struct,
  [790] = 6,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(93), 1,
      anon_sym_0,
    ACTIONS(95), 1,
      aux_sym_decimal_constant_token1,
    STATE(26), 1,
      sym_decimal_constant,
    STATE(69), 1,
      sym_constant,
    ACTIONS(97), 2,
      sym_hexadecimal_constant,
      sym_octal_constant,
  [810] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(105), 6,
      anon_sym_RBRACK,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COLON,
  [822] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      sym_keyword_union,
      sym_keyword_typedef,
      sym_keyword_const,
      sym_keyword_enum,
      sym_keyword_struct,
  [834] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(109), 6,
      anon_sym_RBRACK,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COLON,
  [846] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      sym_keyword_union,
      sym_keyword_typedef,
      sym_keyword_const,
      sym_keyword_enum,
      sym_keyword_struct,
  [858] = 4,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(115), 1,
      sym_keyword_case,
    ACTIONS(113), 2,
      anon_sym_RBRACE,
      sym_keyword_default,
    STATE(30), 2,
      sym_case_spec,
      aux_sym_union_body_repeat1,
  [873] = 5,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(120), 1,
      sym_keyword_case,
    ACTIONS(122), 1,
      sym_keyword_default,
    STATE(30), 2,
      sym_case_spec,
      aux_sym_union_body_repeat1,
  [890] = 5,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(120), 1,
      sym_keyword_case,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    ACTIONS(126), 1,
      sym_keyword_default,
    STATE(31), 2,
      sym_case_spec,
      aux_sym_union_body_repeat1,
  [907] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(128), 5,
      anon_sym_RBRACK,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [918] = 4,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LT,
    ACTIONS(134), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [932] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(136), 3,
      anon_sym_STAR,
      anon_sym_SEMI,
      sym_identifier,
  [941] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(138), 3,
      anon_sym_STAR,
      anon_sym_SEMI,
      sym_identifier,
  [950] = 4,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(43), 1,
      aux_sym_enum_body_repeat1,
  [963] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(144), 3,
      anon_sym_STAR,
      anon_sym_SEMI,
      sym_identifier,
  [972] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(146), 3,
      anon_sym_STAR,
      anon_sym_SEMI,
      sym_identifier,
  [981] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(148), 3,
      anon_sym_STAR,
      anon_sym_SEMI,
      sym_identifier,
  [990] = 4,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_enum_body_repeat1,
  [1003] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(155), 3,
      anon_sym_STAR,
      anon_sym_SEMI,
      sym_identifier,
  [1012] = 4,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_enum_body_repeat1,
  [1025] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(159), 3,
      anon_sym_STAR,
      anon_sym_SEMI,
      sym_identifier,
  [1034] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(161), 3,
      anon_sym_RBRACE,
      sym_keyword_case,
      sym_keyword_default,
  [1043] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(163), 3,
      anon_sym_RBRACE,
      sym_keyword_case,
      sym_keyword_default,
  [1052] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(165), 3,
      anon_sym_STAR,
      anon_sym_SEMI,
      sym_identifier,
  [1061] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(167), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_struct_body,
  [1071] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(169), 1,
      sym_keyword_switch,
    STATE(88), 1,
      sym_union_body,
  [1081] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(171), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1089] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(173), 2,
      anon_sym_STAR,
      sym_identifier,
  [1097] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(175), 2,
      anon_sym_STAR,
      sym_identifier,
  [1105] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(169), 1,
      sym_keyword_switch,
    STATE(66), 1,
      sym_union_body,
  [1115] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_enum_body,
  [1125] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(179), 2,
      anon_sym_int,
      anon_sym_hyper,
  [1133] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LT,
  [1143] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(181), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1151] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(183), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1159] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(185), 2,
      anon_sym_STAR,
      sym_identifier,
  [1167] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(187), 1,
      anon_sym_STAR,
    ACTIONS(189), 1,
      sym_identifier,
  [1177] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(191), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1185] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(88), 1,
      sym_enum_body,
  [1195] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(167), 1,
      anon_sym_LBRACE,
    STATE(88), 1,
      sym_struct_body,
  [1205] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(193), 2,
      anon_sym_STAR,
      sym_identifier,
  [1213] = 3,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(120), 1,
      sym_keyword_case,
    STATE(32), 1,
      sym_case_spec,
  [1223] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(195), 2,
      anon_sym_STAR,
      sym_identifier,
  [1231] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(197), 1,
      anon_sym_GT,
  [1238] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(199), 1,
      sym_identifier,
  [1245] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(201), 1,
      anon_sym_SEMI,
  [1252] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(203), 1,
      anon_sym_EQ,
  [1259] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
  [1266] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(207), 1,
      anon_sym_SEMI,
  [1273] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(209), 1,
      anon_sym_COLON,
  [1280] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(197), 1,
      anon_sym_RBRACK,
  [1287] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(211), 1,
      anon_sym_COLON,
  [1294] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [1301] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(215), 1,
      anon_sym_EQ,
  [1308] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(217), 1,
      sym_identifier,
  [1315] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(219), 1,
      sym_identifier,
  [1322] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
  [1329] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(223), 1,
      anon_sym_COLON,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(225), 1,
      sym_identifier,
  [1343] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(227), 1,
      sym_identifier,
  [1350] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
  [1357] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(231), 1,
      anon_sym_SEMI,
  [1364] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(233), 1,
      anon_sym_SEMI,
  [1371] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(235), 1,
      anon_sym_SEMI,
  [1378] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(237), 1,
      anon_sym_SEMI,
  [1385] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(239), 1,
      anon_sym_COLON,
  [1392] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(241), 1,
      sym_identifier,
  [1399] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(243), 1,
      anon_sym_SEMI,
  [1406] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(245), 1,
      sym_identifier,
  [1413] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(247), 1,
      anon_sym_RBRACE,
  [1420] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(249), 1,
      anon_sym_SEMI,
  [1427] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(251), 1,
      sym_identifier,
  [1434] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(253), 1,
      anon_sym_EQ,
  [1441] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(255), 1,
      anon_sym_SEMI,
  [1448] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
  [1455] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(132), 1,
      anon_sym_LT,
  [1462] = 2,
    ACTIONS(3), 1,
      sym_block_comment,
    ACTIONS(259), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 153,
  [SMALL_STATE(6)] = 204,
  [SMALL_STATE(7)] = 255,
  [SMALL_STATE(8)] = 300,
  [SMALL_STATE(9)] = 345,
  [SMALL_STATE(10)] = 390,
  [SMALL_STATE(11)] = 435,
  [SMALL_STATE(12)] = 480,
  [SMALL_STATE(13)] = 506,
  [SMALL_STATE(14)] = 527,
  [SMALL_STATE(15)] = 550,
  [SMALL_STATE(16)] = 580,
  [SMALL_STATE(17)] = 610,
  [SMALL_STATE(18)] = 636,
  [SMALL_STATE(19)] = 662,
  [SMALL_STATE(20)] = 688,
  [SMALL_STATE(21)] = 714,
  [SMALL_STATE(22)] = 740,
  [SMALL_STATE(23)] = 766,
  [SMALL_STATE(24)] = 778,
  [SMALL_STATE(25)] = 790,
  [SMALL_STATE(26)] = 810,
  [SMALL_STATE(27)] = 822,
  [SMALL_STATE(28)] = 834,
  [SMALL_STATE(29)] = 846,
  [SMALL_STATE(30)] = 858,
  [SMALL_STATE(31)] = 873,
  [SMALL_STATE(32)] = 890,
  [SMALL_STATE(33)] = 907,
  [SMALL_STATE(34)] = 918,
  [SMALL_STATE(35)] = 932,
  [SMALL_STATE(36)] = 941,
  [SMALL_STATE(37)] = 950,
  [SMALL_STATE(38)] = 963,
  [SMALL_STATE(39)] = 972,
  [SMALL_STATE(40)] = 981,
  [SMALL_STATE(41)] = 990,
  [SMALL_STATE(42)] = 1003,
  [SMALL_STATE(43)] = 1012,
  [SMALL_STATE(44)] = 1025,
  [SMALL_STATE(45)] = 1034,
  [SMALL_STATE(46)] = 1043,
  [SMALL_STATE(47)] = 1052,
  [SMALL_STATE(48)] = 1061,
  [SMALL_STATE(49)] = 1071,
  [SMALL_STATE(50)] = 1081,
  [SMALL_STATE(51)] = 1089,
  [SMALL_STATE(52)] = 1097,
  [SMALL_STATE(53)] = 1105,
  [SMALL_STATE(54)] = 1115,
  [SMALL_STATE(55)] = 1125,
  [SMALL_STATE(56)] = 1133,
  [SMALL_STATE(57)] = 1143,
  [SMALL_STATE(58)] = 1151,
  [SMALL_STATE(59)] = 1159,
  [SMALL_STATE(60)] = 1167,
  [SMALL_STATE(61)] = 1177,
  [SMALL_STATE(62)] = 1185,
  [SMALL_STATE(63)] = 1195,
  [SMALL_STATE(64)] = 1205,
  [SMALL_STATE(65)] = 1213,
  [SMALL_STATE(66)] = 1223,
  [SMALL_STATE(67)] = 1231,
  [SMALL_STATE(68)] = 1238,
  [SMALL_STATE(69)] = 1245,
  [SMALL_STATE(70)] = 1252,
  [SMALL_STATE(71)] = 1259,
  [SMALL_STATE(72)] = 1266,
  [SMALL_STATE(73)] = 1273,
  [SMALL_STATE(74)] = 1280,
  [SMALL_STATE(75)] = 1287,
  [SMALL_STATE(76)] = 1294,
  [SMALL_STATE(77)] = 1301,
  [SMALL_STATE(78)] = 1308,
  [SMALL_STATE(79)] = 1315,
  [SMALL_STATE(80)] = 1322,
  [SMALL_STATE(81)] = 1329,
  [SMALL_STATE(82)] = 1336,
  [SMALL_STATE(83)] = 1343,
  [SMALL_STATE(84)] = 1350,
  [SMALL_STATE(85)] = 1357,
  [SMALL_STATE(86)] = 1364,
  [SMALL_STATE(87)] = 1371,
  [SMALL_STATE(88)] = 1378,
  [SMALL_STATE(89)] = 1385,
  [SMALL_STATE(90)] = 1392,
  [SMALL_STATE(91)] = 1399,
  [SMALL_STATE(92)] = 1406,
  [SMALL_STATE(93)] = 1413,
  [SMALL_STATE(94)] = 1420,
  [SMALL_STATE(95)] = 1427,
  [SMALL_STATE(96)] = 1434,
  [SMALL_STATE(97)] = 1441,
  [SMALL_STATE(98)] = 1448,
  [SMALL_STATE(99)] = 1455,
  [SMALL_STATE(100)] = 1462,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_case_spec_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_case_spec_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_case_spec_repeat1, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decimal_constant, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_def, 5, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_body_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_body_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 12, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 5, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_body, 5, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_body, 6, 0, 0),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_body_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_body_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 7, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 8, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_spec, 5, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_spec, 6, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 11, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 5, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_type_spec, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_type_spec, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_body_repeat1, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_specifier, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_specifier, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_type_spec, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_naive_xdr(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "naive_xdr",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
